emoji_name_to_text = {
    "grinningface": "happy smile",
    "smilingfacewithsmilingeyes": "joyful",
    "unitedstates": "america",
    "wrappedgift": "present gift birthday holiday",
    "relievedface": "relieved relaxed content",
    "redheart": "love",
    "signofthehornslightskintone": "rock on rebellious",
    "womanshruggingmediumskintone": "shrug indifference",
    "facewithtearsofjoy": "hilarious funny",
    "heartsuit": "love",
    "crescentmoon": "night sleep",
    "foldedhandsmediumdarkskintone": "prayer",
    "partypopper": "celebration party",
    "moneybag": "money",
    "santaclausmediumlightskintone": "christmas santa",
    "sportutilityvehicle": "car",
    "happywithhalo": "angelic happy",
    "smilingfacewithhearteyes": "love affection",
    "vulcansalutemediumskintone": "prosperity vulcan salute",
    "growingheart": "love joy",
    "faceblowingakiss": "romantic",
    "smilingfacewithsunglasses": "cool confident",
    "smirkingface": "sly playful",
    "neutralface": "neutral indifferent",
    "expressionlessface": "unemotional",
    "facewithoutmouth": "speechless",
    "facewithrollingeyes": "annoyed sarcastic",
    "thinkingface": "thoughtful considering",
    "flushedface": "embarrassed",
    "facescreaminginfear": "shocked scared",
    "astonishedface": "amazed surprised",
    "sleepingface": "sleepy tired",
    "smilingface": "happy",
    "pileofpoo": "joking crappy",
    "clownface": "funny silly",
    "ghost": "spooky scary",
    "skull": "danger pirate",
    "alien": "weird extraterrestrial",
    "robot": "mechanical emotionless",
    "smilingcatwithhearteyes": "cat love cute",
    "seenoevilmonkey": "ignorance playful",
    "hearnoevilmonkey": "deaf unresponsive",
    "speaknoevilmonkey": "silence hush",
    "heartwitharrow": "falling in love",
    "brokenheart": "heartbroken",
    "sparkles": "exciting magical",
    "fire": "hot popular",
    "recyclesymbol": "environmental",
    "musicalnotes": "musical",
    "camerawithflash": "photography",
    "sunbehindsmallcloud": "partly sunny",
    "snowmanwithoutsnow": "winter",
    "umbrellawithraindrops": "rainy",
    "coffee": "coffee break",
    "hamburger": "fast food",
    "pizza": "party food",
    "beermug": "drinks party",
    "clinkingbeermugs": "cheers",
    "jackolantern": "halloween",
    "christmastree": "christmas",
    "fireworks": "celebration",
    "winkingfacewithtongue": "playful teasing",
    "raisinghandsmediumlightskintone": "celebration praise",
    "sparkler": "festive",
    "cowboyhatface": "cowboy country",
    "princessmediumlightskintone": "princess",
    "redheart": "love",
    "sweatdroplets": "physical activity",
    "signofthehornslightskintone": "metal rebellious rock on",
    "cherryblossom": "spring beauty",
    "smilingfacewithhorns": "mischief",
    "persongesturingoklightskintone": "approval okay",
    "okhandmediumlightskintone": "okay perfect",
    "flexedbicepsmediumlightskintone": "strength power gym",
    "callmehandmediumlightskintone": "call me contact",
    "squintingfacewithtongue": "playful teasing",
    "smilingfacewithhalo": "innocent angelic",
    "womanshruggingmediumlightskintone": "shrug indifference",
    "signofthehornsmediumlightskintone": "rock on rebellious",
    "moneymouthface": "money-driven greedy",
    "womandancingmediumskintone": "party celebration",
    "flexedbicepsmediumskintone": "strength power gym",
    "droolingface": "desire craving",
    "persongesturingokmediumlightskintone": "approval okay",
    "waterwave": "sea vacation",
    "okhandlightskinton": "perfect okay",
    "middlefingermediumlightskintone": "disdain rebellious",
    "twohearts": "love affection",
    "hundredpoints": "perfect score excellence",
    "facesavoringfood": "delicious tasty",
    "okhandlightskinto": "all good satisfactory",
    "personrunninglightskintone": "running",
    "womandancingmediumlightskintone": "danse",
    "signofthehornsmediumskintone": "metal rebellious",
    "bottlewithpoppingcork": "celebration toast",
    "womandancing": "dance freedom",
    "okhanddarkskintone": "all good",
    "middlefingerlightskintone": "rude gesture",
    "musicalnote": "music love",
    "christianworship": "spiritual worship",
    "yellowheart": "friendship",
    "smilingfacewithopenhands": "hug positive friendship",
    "flexedbiceps": "strength power gym",
    "hundredpoints": "perfect score excellence",
    "loudlycryingface": "sad upset",
    "pensiveface": "thoughtful",
    "womandancinglightskintone": "dance freedom",
    "facesavoringfood": "delicious tasty food",
    "thoughtballoon": "thinking sadness",
    "smilingfacewithhalo": "innocent angelic",
    "twohearts": "love affection",
    "persontippinghandlightskintone": "sassy tipping",
    "highvoltage": "high energy",
    "revolvinghearts": "love affection",
    "pirateandcrossbones": "danger pirate",
    "backhandindexpointingright": "direction",
    "upsidedownface": "silly playful",
}
